import os
import re
import json
from pathlib import Path
from bs4 import BeautifulSoup

EXPORT_DIR = "SparxEA_HTML_Export"
IGNORED_FILES = {"index.htm", "blank.htm", "toc.htm", "EAID_9BC9448B_98C1_4215_A154_D41E80507030.htm", "EAID_808A1CDA_04E7_4d37_B12F_93F3E2023788.htm"}

JS_FOLDER = os.path.join(EXPORT_DIR, "js")
os.makedirs(JS_FOLDER, exist_ok=True)

INDEX_JS_PATH = os.path.join(JS_FOLDER, "searchIndex.js")
LOGIC_JS_PATH = os.path.join(JS_FOLDER, "searchLogic.js")

LUNR_CDN = "https://unpkg.com/lunr/lunr.js"

def gather_documents():
    docs = []
    for root, dirs, files in os.walk(EXPORT_DIR):
        for fname in files:
            if fname.lower().endswith(".htm") and fname not in IGNORED_FILES:
                fpath   = os.path.join(root, fname)
                relpath = os.path.relpath(fpath, EXPORT_DIR).replace("\\", "/")
                with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                soup = BeautifulSoup(content, "html.parser")
                for tag in soup(["script", "style"]):
                    tag.extract()
                text_body = soup.get_text(separator=" ")
                text_body = re.sub(r"\s+", " ", text_body).strip()
                title_tag = soup.find("title")
                if title_tag and title_tag.string:
                    page_title = title_tag.string.strip()
                else:
                    page_title = fname
                docs.append({
                    "id": relpath,
                    "text": text_body,
                    "title": page_title
                })
    return docs

def write_search_index_js(docs):
    with open(INDEX_JS_PATH, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by main.py\n")
        f.write("var documents = ")
        f.write(json.dumps(docs, ensure_ascii=False))
        f.write(";\n\n")
        f.write("var docDictionary = {};\n")
        f.write("documents.forEach(function(d){\n")
        f.write("  docDictionary[d.id] = { title: d.title };\n")
        f.write("});\n\n")
        f.write("""(function(){
  window.idx = lunr(function () {
    this.ref('id');
    this.field('text');
    documents.forEach(doc => this.add(doc), this);
  });
})();
""")

def write_search_logic_js():
    with open(LOGIC_JS_PATH, "w", encoding="utf-8") as f:
        f.write("""function doLunrSearch(query) {
  if (!window.idx) return [];
  return window.idx.search(query);
}

// currentPageId should be passed in from each page, indicating its relative path
function handleSearchInput(el, currentPageId) {
  const query = el.value.trim();
  if (!query) {
    // If the search field is empty, display nothing (or whatever you like).
    document.getElementById('lunrSearchResults').innerHTML = "";
    return;
  }

  const results = doLunrSearch(query);
  let output = "";
  results.forEach(r => {
    const docId = r.ref;
    const docMeta = window.docDictionary[docId];
    const docTitle = docMeta ? docMeta.title : docId;
    const link = buildRelativeLink(currentPageId, docId);
    output += `<div><a href="${link}" target="_blank">${docTitle}</a></div>`;
  });
  document.getElementById('lunrSearchResults').innerHTML = output;
}

// Reconstruct a relative link so that we don't duplicate subfolders
function buildRelativeLink(fromId, toId) {
  if (!fromId || !toId) return toId;
  const fromParts = fromId.split('/');
  fromParts.pop(); // remove current file name
  const toParts = toId.split('/');
  // Remove any empty parts
  const fromStack = [];
  fromParts.forEach(p => { if(p) fromStack.push(p); });
  const toStack = [];
  toParts.forEach(p => { if(p) toStack.push(p); });

  // find common prefix
  let i = 0;
  while (i < fromStack.length && i < toStack.length && fromStack[i] === toStack[i]) {
    i++;
  }
  // how many folders to go up from "from"
  const ups = fromStack.length - i;
  let relative = "";
  for (let j = 0; j < ups; j++) {
    relative += "../";
  }
  // then down into the "to" remainder
  const downs = toStack.slice(i).join("/");
  relative += downs;
  return relative;
}
""")

def inject_search_bar():
    """
    Injects the search bar + scripts into all *.htm, but only if 'id="lunrSearchBar"'
    is NOT already present. This avoids duplicates on index.htm or anywhere else.
    """
    import re

    head_pattern = re.compile(r"</head>", flags=re.IGNORECASE)
    body_pattern = re.compile(r"<body([^>]*)>", flags=re.IGNORECASE)

    for root, dirs, files in os.walk(EXPORT_DIR):
        for fname in files:
            if fname.lower().endswith(".htm"):
                fpath = os.path.join(root, fname)

                with open(fpath, "r", encoding="utf-8", errors="ignore") as fr:
                    html = fr.read()

                # If the page already has a search bar, skip
                if 'id="lunrSearchBar"' in html:
                    continue

                # Figure out how deep we are:
                relpath = os.path.relpath(fpath, EXPORT_DIR)
                rel_parts = relpath.split(os.sep)
                depth = len(rel_parts) - 1
                up_levels = "../" * depth if depth > 0 else "./"

                script_inject = f"""
  <script src="{LUNR_CDN}"></script>
  <script src="{up_levels}js/searchIndex.js"></script>
  <script src="{up_levels}js/searchLogic.js"></script>
  </head>
"""

                # Insert <script> references near </head>
                def replace_head(_match):
                    return script_inject

                if head_pattern.search(html):
                    html = head_pattern.sub(replace_head, html, count=1)
                else:
                    # fallback to prepend if no </head>
                    html = script_inject + html

                # Insert currentPageId
                current_page_script = f"""
<script>
  var currentPageId = "{relpath.replace('\\\\','/')}";
</script>
"""

                # The search bar snippet
                search_div = f"""
{current_page_script}
<div id="lunrSearchBar" style="margin:10px;">
  <input type="text" oninput="handleSearchInput(this, currentPageId)" placeholder="Search..." />
  <div id="lunrSearchResults" style="margin-top:5px;"></div>
</div>
"""

                def replace_body(m):
                    return f"<body{m.group(1)}>{search_div}"

                if body_pattern.search(html):
                    html = body_pattern.sub(replace_body, html, count=1)
                else:
                    # fallback if no <body>
                    html = search_div + html

                with open(fpath, "w", encoding="utf-8") as fw:
                    fw.write(html)

def main():
    docs = gather_documents()
    write_search_index_js(docs)
    write_search_logic_js()
    inject_search_bar()

if __name__ == "__main__":
    main()
